# Generated by Django 6.0.8 on 2026-08-19 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], max_length=10, null=True)),
                ('channel', models.CharField(blank=True, choices=[('direct', 'Direct'), ('organic', 'Organic search'), ('paid', 'Paid'), ('social', 'Social'), ('referral', 'Referral'), ('email', 'Email'), ('internal', 'Internal')], max_length=20, null=True)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('bounces', models.PositiveIntegerField(default=0)),
                ('total_engaged_seconds', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date', 'path'], name='analytics_ds_date_path'), models.Index(fields=['-date', 'country'], name='analytics_ds_country'), models.Index(fields=['-date', 'channel'], name='analytics_ds_channel')],
                'unique_together': {('date', 'path', 'country', 'device_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('failed_login', 'Failed login'), ('rate_limit', 'Rate limit hit'), ('path_scan', 'Path scan'), ('enumeration', 'ID enumeration'), ('suspicious_ua', 'Suspicious user agent')], db_index=True, max_length=20)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_truncated', models.GenericIPAddressField(blank=True, null=True)),
                ('asn', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('username_attempted', models.CharField(blank=True, max_length=150)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['kind', '-occurred_at'], name='analytics_sec_kind'), models.Index(fields=['ip_hash', '-occurred_at'], name='analytics_sec_ip')],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('first_touch_channel', models.CharField(blank=True, choices=[('direct', 'Direct'), ('organic', 'Organic search'), ('paid', 'Paid'), ('social', 'Social'), ('referral', 'Referral'), ('email', 'Email'), ('internal', 'Internal')], max_length=20)),
                ('first_touch_source', models.CharField(blank=True, max_length=120)),
                ('first_touch_campaign', models.CharField(blank=True, max_length=120)),
                ('last_touch_channel', models.CharField(blank=True, choices=[('direct', 'Direct'), ('organic', 'Organic search'), ('paid', 'Paid'), ('social', 'Social'), ('referral', 'Referral'), ('email', 'Email'), ('internal', 'Internal')], max_length=20)),
                ('last_touch_source', models.CharField(blank=True, max_length=120)),
                ('last_touch_campaign', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(blank=True, help_text='Attached on login, so an authenticated session can be traced back to the anonymous activity that preceded it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('landing_path', models.CharField(blank=True, max_length=200)),
                ('exit_path', models.CharField(blank=True, max_length=200)),
                ('referrer_host', models.CharField(blank=True, max_length=120)),
                ('referrer_url', models.CharField(blank=True, max_length=500)),
                ('channel', models.CharField(choices=[('direct', 'Direct'), ('organic', 'Organic search'), ('paid', 'Paid'), ('social', 'Social'), ('referral', 'Referral'), ('email', 'Email'), ('internal', 'Internal')], default='direct', max_length=20)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('utm_term', models.CharField(blank=True, max_length=120)),
                ('utm_content', models.CharField(blank=True, max_length=120)),
                ('click_id', models.CharField(blank=True, help_text='gclid, fbclid or msclkid, whichever was present on landing.', max_length=120, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('tz_from_ip', models.CharField(blank=True, max_length=64)),
                ('asn', models.CharField(blank=True, max_length=16)),
                ('asn_org', models.CharField(blank=True, max_length=160)),
                ('is_datacenter', models.BooleanField(default=False)),
                ('browser', models.CharField(blank=True, max_length=60)),
                ('browser_version', models.CharField(blank=True, max_length=30)),
                ('os', models.CharField(blank=True, max_length=60)),
                ('os_version', models.CharField(blank=True, max_length=30)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_truncated', models.GenericIPAddressField(blank=True, help_text='IPv4 with the last octet zeroed, IPv6 with the last 80 bits zeroed. Coarse enough not to identify a household, precise enough to group an abusive network.', null=True)),
                ('language', models.CharField(blank=True, max_length=35)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('bot_reason', models.CharField(blank=True, max_length=60)),
                ('pageview_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_bounce', models.BooleanField(default=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_key', models.CharField(db_index=True, max_length=60)),
                ('variant', models.CharField(max_length=40)),
                ('assigned_at', models.DateTimeField()),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_assignments', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('normalized_query', models.CharField(db_index=True, help_text='Lowercased and whitespace-collapsed, so the report groups "Django" and "  django " as one query.', max_length=200)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('clicked_result', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='analytics.session')),
            ],
            options={
                'verbose_name_plural': 'Search queries',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['result_count', '-occurred_at'], name='analytics_sq_zero'), models.Index(fields=['normalized_query'], name='analytics_sq_norm')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=200)),
                ('query_hash', models.CharField(blank=True, help_text='Hash of the non-allowlisted query string. Never the raw value, so a token pasted into a URL is not stored.', max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('referrer_url', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('engaged_seconds', models.PositiveIntegerField(blank=True, help_text='Visible, interacted-with time from the beacon. Not wall clock: a tab left open in the background accrues nothing.', null=True)),
                ('max_scroll_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_spa_navigation', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.session')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['path', '-occurred_at'], name='analytics_pv_path'), models.Index(fields=['session', '-occurred_at'], name='analytics_pv_session'), models.Index(fields=['status_code'], name='analytics_pv_status')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.session')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['name', '-occurred_at'], name='analytics_ev_name'), models.Index(fields=['session', '-occurred_at'], name='analytics_ev_session')],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['-last_seen_at'], name='analytics_vis_lastseen'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['is_bot', '-last_seen_at'], name='analytics_vis_bot'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['visitor', '-started_at'], name='analytics_ses_visitor'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['-started_at', 'channel'], name='analytics_ses_channel'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['ended_at'], name='analytics_ses_open'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_bot', '-started_at'], name='analytics_ses_bot'),
        ),
        migrations.AddIndex(
            model_name='experimentassignment',
            index=models.Index(fields=['experiment_key', 'variant'], name='analytics_exp_variant'),
        ),
        migrations.AlterUniqueTogether(
            name='experimentassignment',
            unique_together={('visitor', 'experiment_key')},
        ),
    ]
