# Generated by Django 6.0.8 on 2026-08-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_visitor_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='import_source',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
