# Generated by Django 6.0.8 on 2026-08-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Whether the address is routable on the public internet.')),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('last_path', models.CharField(blank=True, max_length=200)),
                ('last_user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-last_seen'],
            },
        ),
    ]
