# Generated by Django 6.0.8 on 2026-08-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
