"""
Django settings for yzwebsiteproject project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import re
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Compiled React bundle. Django serves it, so the site and the admin share one
# origin and the API needs no CORS in production.
FRONTEND_DIST_DIR = BASE_DIR / 'frontend' / 'dist'


def get_env_flag(name, default):
    return os.environ.get(name, default).strip().lower() in {'1', 'true', 'yes'}


def get_env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


DEBUG = get_env_flag('DJANGO_DEBUG', 'True')

# A missing secret must never silently fall back to a published value, so the
# development key is only ever available while DEBUG is on.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DEBUG is disabled.'
        )
    SECRET_KEY = 'django-insecure-local-development-key-not-for-deployment'

# The admin is the only authenticated surface on this site, so its location is
# treated as part of the credential: sweeps of '/admin/' are constant and every
# one of them is a login attempt a moved admin never has to answer. The real
# path is read from the environment rather than written here for the same
# reason SECRET_KEY is — the repository is public.
#
# Development gets a placeholder so a fresh checkout runs with no setup, but it
# is deliberately not 'admin': there is no configuration of this project, in
# any environment, that serves the panel from the one path every scanner
# already knows.
DEV_ADMIN_URL_SEGMENT = 'dev-admin'

# A missing value must never fall back to a published path, so the development
# segment is only ever available while DEBUG is on — the same rule SECRET_KEY
# follows above, for the same reason.
ADMIN_URL_SEGMENT = os.environ.get('DJANGO_ADMIN_URL', '').strip().strip('/')
if not ADMIN_URL_SEGMENT:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_ADMIN_URL must be set when DEBUG is disabled.'
        )
    ADMIN_URL_SEGMENT = DEV_ADMIN_URL_SEGMENT

# Whitelisted rather than escaped at the point of use: the segment is
# interpolated into a URL regex, and a value that cannot hold a metacharacter
# cannot change what that pattern matches.
if not re.fullmatch(r'[A-Za-z0-9_-]{1,64}', ADMIN_URL_SEGMENT):
    raise ImproperlyConfigured(
        'DJANGO_ADMIN_URL must be 1-64 characters drawn from letters, digits, '
        'hyphens and underscores.'
    )

if ADMIN_URL_SEGMENT.lower() == 'admin':
    raise ImproperlyConfigured(
        "DJANGO_ADMIN_URL must not be 'admin'. Moving the panel off that path "
        'is the whole purpose of the setting.'
    )

# Prefixes Django owns rather than the SPA. The root URLconf keeps them out of
# its catch-all and the analytics collector drops requests under them. Nothing
# is reserved for the admin's former location: once moved, '/admin/' is an
# ordinary unknown path and the SPA answers it like any other.
BACKEND_URL_PREFIXES = (ADMIN_URL_SEGMENT, 'api', 'static')

ALLOWED_HOSTS = get_env_list('DJANGO_ALLOWED_HOSTS')
if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1', '[::1]']

# Render exposes the service's public hostname at runtime.
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Admin logins post across HTTPS, so the served origins must be trusted.
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS if '.' in host]

if not DEBUG:
    # Render terminates TLS upstream; without this Django believes it is on HTTP.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Opt-out exists so a production-mode build can be smoke-tested over plain
    # HTTP locally without every response turning into an HTTPS redirect.
    SECURE_SSL_REDIRECT = get_env_flag('DJANGO_SECURE_SSL_REDIRECT', 'True')
    SESSION_COOKIE_SECURE = SECURE_SSL_REDIRECT
    CSRF_COOKIE_SECURE = SECURE_SSL_REDIRECT

    # Deliberately one hour rather than a year: browsers honour HSTS for the
    # full duration and refuse plain HTTP for the domain, so a short window
    # keeps a misconfiguration recoverable. Raise it once HTTPS is proven.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '3600'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'api',
    'analytics',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be placed before CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serves static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Resolves the visitor's consent state once, before anything reads it.
    'analytics.middleware.ConsentMiddleware',
    # Last so it only records requests that made it through every other layer.
    # Replaces api.middleware.VisitorTrackingMiddleware, which wrote to the
    # database on the response; this one only appends to an in-process buffer.
    'analytics.middleware.CollectorMiddleware',
]

# How many reverse proxies sit in front of Django, which fixes how much of
# X-Forwarded-For was written by our own infrastructure rather than by the
# visitor. Render terminates TLS at one proxy hop; running the dev server
# locally there is none, and REMOTE_ADDR is already the true peer. Setting this
# higher than the real hop count lets a visitor forge their recorded address.
TRUSTED_PROXY_COUNT = int(
    os.environ.get('DJANGO_TRUSTED_PROXY_COUNT', '0' if DEBUG else '1')
)

ROOT_URLCONF = 'yzwebsiteproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # The built index.html is rendered as a template so the SPA can be
        # returned from Django's own URL routing.
        'DIRS': [BASE_DIR / 'templates', FRONTEND_DIST_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yzwebsiteproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Container filesystems are wiped on redeploy, so a deployed instance must be
# pointed at a managed database via DATABASE_URL or it will lose every message.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# The Vite build references its assets from the root ('/assets/...'), so the
# bundle is served straight from its own directory rather than being collected
# under STATIC_URL. That keeps the compiled output host-agnostic: the identical
# files work behind Django, `vite preview`, or any plain static host.
if FRONTEND_DIST_DIR.is_dir():
    WHITENOISE_ROOT = FRONTEND_DIST_DIR

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compressed, but deliberately not the manifest variant: manifest storage
        # renames files, which would break the asset URLs already baked into the
        # prebuilt index.html. Vite content-hashes its own filenames anyway.
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# CORS configuration — allows React dev server to call this Django backend
# ---------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   # Create React App default port
    "http://127.0.0.1:3000",
    "http://localhost:5173",   # Vite default port
    "http://127.0.0.1:5173",
    "https://yannzakpa.space",       # Production site
    "https://www.yannzakpa.space",
]


# ---------------------------------------------------------------------------
# Analytics
# ---------------------------------------------------------------------------
ANALYTICS = {
    # Stated rather than left to the app's default, which hardcodes '/admin/'
    # and would otherwise start collecting the moved admin's traffic.
    'EXCLUDE_PATH_PREFIXES': [f'/{prefix}/' for prefix in BACKEND_URL_PREFIXES]
    + ['/assets/', '/media/'],
}


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
# Without an explicit configuration Django leaves the root logger to logging's
# handler of last resort, which writes WARNING and above and drops everything
# below. That makes the analytics pipeline invisible in production: it runs its
# writes on a background thread, so nothing about whether that thread started,
# or how much it wrote, ever reaches a request or a response. Diagnosing it
# then depends on the one thing that is not logged.
#
# Gunicorn hands stdout and stderr to the platform's log stream, so a plain
# console handler is all that is needed on Render.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # INFO by default so the pipeline reports the thread starting and each
        # non-empty flush. The volume is one line per five seconds at most, and
        # only when there is traffic to write.
        'analytics': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_ANALYTICS_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_RATES': {
        # Public, unauthenticated contact form — limit abuse per IP address.
        'contact_form': '10/hour',
    },
}